"""
Demo Scenarios for AgriNet India.
Provides deterministic, plausible demonstration data for 5 Indian states.
These are DEMO scenarios — NOT live observations.
Used when external APIs are unavailable or for demonstration purposes.
"""

SCENARIOS = {
    "agra_wheat": {
        "name": "Agra, Uttar Pradesh",
        "state": "Uttar Pradesh",
        "crop": "Wheat",
        "lat": 27.1767,
        "lon": 78.0081,
        "land": {
            "source": "demo",
            "resolution": "Demo scenario",
            "observed": "2024-02-15",
            "land_cover_id": 4,
            "land_cover": "crops",
            "label_origin": "Demo scenario (Agra wheat belt)",
            "is_cropland": True,
            "geohash": "ttt8u0v",
            "ndvi_latest": 0.62,
            "ndwi_latest": 0.18,
            "ndvi_series": [
                {"date": "2024-01-01", "ndvi": 0.34},
                {"date": "2024-01-15", "ndvi": 0.42},
                {"date": "2024-01-28", "ndvi": 0.51},
                {"date": "2024-02-05", "ndvi": 0.58},
                {"date": "2024-02-15", "ndvi": 0.62},
            ],
            "ndwi_series": [
                {"date": "2024-01-01", "ndwi": 0.08},
                {"date": "2024-01-15", "ndwi": 0.12},
                {"date": "2024-01-28", "ndwi": 0.15},
                {"date": "2024-02-05", "ndwi": 0.17},
                {"date": "2024-02-15", "ndwi": 0.18},
            ],
            "confidence": 0.72,
            "model_prediction": {
                "land_cover": "crops",
                "confidence": 0.68,
                "top3": [
                    {"class": "crops", "p": 0.68},
                    {"class": "grass", "p": 0.18},
                    {"class": "bare", "p": 0.08},
                ],
                "agrees_with_label": True,
                "model": "SPEAR PlanetScope MAE (32-d) + head",
            },
        },
        "weather": {
            "days": [f"2024-02-{d:02d}" for d in range(9, 23)],
            "tmax": [28, 29, 31, 30, 32, 33, 31, 29, 30, 31, 33, 34, 32, 31],
            "tmin": [12, 13, 14, 13, 15, 16, 14, 12, 13, 14, 16, 17, 15, 14],
            "rain_mm": [0, 0, 2.1, 0, 0, 0, 4.2, 0, 0, 0, 0, 0, 3.5, 0],
            "past7_rain_mm": 6.3,
            "next7_rain_mm": 3.5,
        },
        "soil": {
            "topsoil_0_5cm": {
                "phh2o": 7.8,
                "soc": 6.2,
                "nitrogen": 0.8,
                "clay": 280,
                "sand": 420,
            },
            "source": "SoilGrids (ISRIC)",
        },
    },
    "punjab_rice": {
        "name": "Ludhiana, Punjab",
        "state": "Punjab",
        "crop": "Rice",
        "lat": 30.9010,
        "lon": 75.8573,
        "land": {
            "source": "demo",
            "resolution": "Demo scenario",
            "observed": "2024-07-20",
            "land_cover_id": 4,
            "land_cover": "crops",
            "label_origin": "Demo scenario (Punjab rice belt)",
            "is_cropland": True,
            "geohash": "ttnnvxy",
            "ndvi_latest": 0.71,
            "ndwi_latest": 0.35,
            "ndvi_series": [
                {"date": "2024-06-10", "ndvi": 0.25},
                {"date": "2024-06-25", "ndvi": 0.38},
                {"date": "2024-07-05", "ndvi": 0.52},
                {"date": "2024-07-15", "ndvi": 0.65},
                {"date": "2024-07-20", "ndvi": 0.71},
            ],
            "ndwi_series": [
                {"date": "2024-06-10", "ndwi": 0.15},
                {"date": "2024-06-25", "ndwi": 0.22},
                {"date": "2024-07-05", "ndwi": 0.28},
                {"date": "2024-07-15", "ndwi": 0.33},
                {"date": "2024-07-20", "ndwi": 0.35},
            ],
            "confidence": 0.78,
            "model_prediction": {
                "land_cover": "crops",
                "confidence": 0.75,
                "top3": [
                    {"class": "crops", "p": 0.75},
                    {"class": "flooded_vegetation", "p": 0.12},
                    {"class": "grass", "p": 0.08},
                ],
                "agrees_with_label": True,
                "model": "SPEAR PlanetScope MAE (32-d) + head",
            },
        },
        "weather": {
            "days": [f"2024-07-{d:02d}" for d in range(14, 28)],
            "tmax": [35, 36, 34, 33, 35, 36, 37, 34, 33, 35, 36, 34, 33, 35],
            "tmin": [26, 27, 25, 24, 26, 27, 28, 25, 24, 26, 27, 25, 24, 26],
            "rain_mm": [12, 0, 25, 8, 0, 0, 15, 3, 0, 18, 0, 5, 22, 0],
            "past7_rain_mm": 60.0,
            "next7_rain_mm": 48.0,
        },
        "soil": {
            "topsoil_0_5cm": {
                "phh2o": 7.2,
                "soc": 8.5,
                "nitrogen": 1.1,
                "clay": 320,
                "sand": 350,
            },
            "source": "SoilGrids (ISRIC)",
        },
    },
    "maharashtra_cotton": {
        "name": "Nashik, Maharashtra",
        "state": "Maharashtra",
        "crop": "Cotton",
        "lat": 19.9975,
        "lon": 73.7898,
        "land": {
            "source": "demo",
            "resolution": "Demo scenario",
            "observed": "2024-08-10",
            "land_cover_id": 4,
            "land_cover": "crops",
            "label_origin": "Demo scenario (Maharashtra cotton region)",
            "is_cropland": True,
            "geohash": "te6pj83",
            "ndvi_latest": 0.45,
            "ndwi_latest": 0.08,
            "ndvi_series": [
                {"date": "2024-06-15", "ndvi": 0.15},
                {"date": "2024-07-01", "ndvi": 0.28},
                {"date": "2024-07-15", "ndvi": 0.35},
                {"date": "2024-08-01", "ndvi": 0.41},
                {"date": "2024-08-10", "ndvi": 0.45},
            ],
            "ndwi_series": [
                {"date": "2024-06-15", "ndwi": -0.05},
                {"date": "2024-07-01", "ndwi": 0.02},
                {"date": "2024-07-15", "ndwi": 0.05},
                {"date": "2024-08-01", "ndwi": 0.07},
                {"date": "2024-08-10", "ndwi": 0.08},
            ],
            "confidence": 0.61,
            "model_prediction": {
                "land_cover": "crops",
                "confidence": 0.55,
                "top3": [
                    {"class": "crops", "p": 0.55},
                    {"class": "shrub_scrub", "p": 0.22},
                    {"class": "grass", "p": 0.15},
                ],
                "agrees_with_label": True,
                "model": "SPEAR PlanetScope MAE (32-d) + head",
            },
        },
        "weather": {
            "days": [f"2024-08-{d:02d}" for d in range(4, 18)],
            "tmax": [31, 30, 32, 33, 31, 30, 29, 31, 32, 30, 29, 31, 32, 30],
            "tmin": [22, 21, 23, 24, 22, 21, 20, 22, 23, 21, 20, 22, 23, 21],
            "rain_mm": [5, 0, 0, 3, 8, 0, 0, 0, 0, 2, 0, 0, 5, 0],
            "past7_rain_mm": 16.0,
            "next7_rain_mm": 7.0,
        },
        "soil": {
            "topsoil_0_5cm": {
                "phh2o": 6.8,
                "soc": 4.8,
                "nitrogen": 0.6,
                "clay": 450,
                "sand": 220,
            },
            "source": "SoilGrids (ISRIC)",
        },
    },
    "andhra_rice": {
        "name": "Guntur, Andhra Pradesh",
        "state": "Andhra Pradesh",
        "crop": "Rice",
        "lat": 16.3067,
        "lon": 80.4365,
        "land": {
            "source": "demo",
            "resolution": "Demo scenario",
            "observed": "2024-09-05",
            "land_cover_id": 4,
            "land_cover": "crops",
            "label_origin": "Demo scenario (AP coastal rice)",
            "is_cropland": True,
            "geohash": "tephk2w",
            "ndvi_latest": 0.68,
            "ndwi_latest": 0.28,
            "ndvi_series": [
                {"date": "2024-07-20", "ndvi": 0.22},
                {"date": "2024-08-05", "ndvi": 0.38},
                {"date": "2024-08-15", "ndvi": 0.52},
                {"date": "2024-08-28", "ndvi": 0.61},
                {"date": "2024-09-05", "ndvi": 0.68},
            ],
            "ndwi_series": [
                {"date": "2024-07-20", "ndwi": 0.10},
                {"date": "2024-08-05", "ndwi": 0.18},
                {"date": "2024-08-15", "ndwi": 0.22},
                {"date": "2024-08-28", "ndwi": 0.26},
                {"date": "2024-09-05", "ndwi": 0.28},
            ],
            "confidence": 0.74,
            "model_prediction": {
                "land_cover": "crops",
                "confidence": 0.71,
                "top3": [
                    {"class": "crops", "p": 0.71},
                    {"class": "flooded_vegetation", "p": 0.15},
                    {"class": "grass", "p": 0.09},
                ],
                "agrees_with_label": True,
                "model": "SPEAR PlanetScope MAE (32-d) + head",
            },
        },
        "weather": {
            "days": [f"2024-08-{d:02d}" for d in range(30, 32)] + [f"2024-09-{d:02d}" for d in range(1, 13)],
            "tmax": [33, 34, 33, 32, 34, 35, 33, 32, 33, 34, 33, 32, 34, 33],
            "tmin": [24, 25, 24, 23, 25, 26, 24, 23, 24, 25, 24, 23, 25, 24],
            "rain_mm": [15, 8, 0, 22, 10, 0, 5, 0, 12, 0, 18, 0, 8, 5],
            "past7_rain_mm": 60.0,
            "next7_rain_mm": 43.0,
        },
        "soil": {
            "topsoil_0_5cm": {
                "phh2o": 6.5,
                "soc": 7.2,
                "nitrogen": 0.9,
                "clay": 380,
                "sand": 280,
            },
            "source": "SoilGrids (ISRIC)",
        },
    },
    "tamilnadu_groundnut": {
        "name": "Villupuram, Tamil Nadu",
        "state": "Tamil Nadu",
        "crop": "Groundnut",
        "lat": 11.9394,
        "lon": 79.4930,
        "land": {
            "source": "demo",
            "resolution": "Demo scenario",
            "observed": "2024-10-15",
            "land_cover_id": 4,
            "land_cover": "crops",
            "label_origin": "Demo scenario (TN groundnut belt)",
            "is_cropland": True,
            "geohash": "tf2nmkz",
            "ndvi_latest": 0.38,
            "ndwi_latest": 0.05,
            "ndvi_series": [
                {"date": "2024-09-01", "ndvi": 0.18},
                {"date": "2024-09-15", "ndvi": 0.25},
                {"date": "2024-10-01", "ndvi": 0.32},
                {"date": "2024-10-10", "ndvi": 0.36},
                {"date": "2024-10-15", "ndvi": 0.38},
            ],
            "ndwi_series": [
                {"date": "2024-09-01", "ndwi": -0.02},
                {"date": "2024-09-15", "ndwi": 0.01},
                {"date": "2024-10-01", "ndwi": 0.03},
                {"date": "2024-10-10", "ndwi": 0.04},
                {"date": "2024-10-15", "ndwi": 0.05},
            ],
            "confidence": 0.58,
            "model_prediction": {
                "land_cover": "crops",
                "confidence": 0.48,
                "top3": [
                    {"class": "crops", "p": 0.48},
                    {"class": "bare", "p": 0.28},
                    {"class": "shrub_scrub", "p": 0.15},
                ],
                "agrees_with_label": True,
                "model": "SPEAR PlanetScope MAE (32-d) + head",
            },
        },
        "weather": {
            "days": [f"2024-10-{d:02d}" for d in range(9, 23)],
            "tmax": [33, 32, 34, 35, 33, 32, 31, 33, 34, 32, 31, 33, 34, 32],
            "tmin": [24, 23, 25, 26, 24, 23, 22, 24, 25, 23, 22, 24, 25, 23],
            "rain_mm": [0, 0, 3, 0, 0, 0, 0, 0, 2, 0, 0, 0, 4, 0],
            "past7_rain_mm": 3.0,
            "next7_rain_mm": 6.0,
        },
        "soil": {
            "topsoil_0_5cm": {
                "phh2o": 6.2,
                "soc": 3.8,
                "nitrogen": 0.5,
                "clay": 180,
                "sand": 550,
            },
            "source": "SoilGrids (ISRIC)",
        },
    },
}


# Network metadata for all states
NETWORK_STATES = [
    {
        "id": "uttar_pradesh",
        "name": "Uttar Pradesh",
        "code": "UP",
        "scenario_key": "agra_wheat",
        "lat": 27.18,
        "lon": 78.01,
        "sample_crop": "Wheat",
        "sample_city": "Agra",
        "agro_zone": "Indo-Gangetic Plains",
        "status": "pilot",
    },
    {
        "id": "punjab",
        "name": "Punjab",
        "code": "PB",
        "scenario_key": "punjab_rice",
        "lat": 30.90,
        "lon": 75.86,
        "sample_crop": "Rice",
        "sample_city": "Ludhiana",
        "agro_zone": "Trans-Gangetic Plains",
        "status": "pilot",
    },
    {
        "id": "maharashtra",
        "name": "Maharashtra",
        "code": "MH",
        "scenario_key": "maharashtra_cotton",
        "lat": 20.00,
        "lon": 73.79,
        "sample_crop": "Cotton",
        "sample_city": "Nashik",
        "agro_zone": "Western Plateau & Hills",
        "status": "pilot",
    },
    {
        "id": "andhra_pradesh",
        "name": "Andhra Pradesh",
        "code": "AP",
        "scenario_key": "andhra_rice",
        "lat": 16.31,
        "lon": 80.44,
        "sample_crop": "Rice",
        "sample_city": "Guntur",
        "agro_zone": "East Coast Plains & Hills",
        "status": "pilot",
    },
    {
        "id": "tamil_nadu",
        "name": "Tamil Nadu",
        "code": "TN",
        "scenario_key": "tamilnadu_groundnut",
        "lat": 11.94,
        "lon": 79.49,
        "sample_crop": "Groundnut",
        "sample_city": "Villupuram",
        "agro_zone": "East Coast Plains & Hills",
        "status": "pilot",
    },
]


def get_scenario(key: str) -> dict | None:
    """Get a demo scenario by key. Returns None if not found."""
    return SCENARIOS.get(key)


def list_scenarios() -> list:
    """List all available scenarios with minimal metadata."""
    return [
        {
            "key": k,
            "name": v["name"],
            "state": v["state"],
            "crop": v["crop"],
            "lat": v["lat"],
            "lon": v["lon"],
        }
        for k, v in SCENARIOS.items()
    ]
